version: "3.8"
services:
  dev-db:
    image: "postgres:16.3-alpine3.20"
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: beers
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
