export default [
  {
    id: 1,
    brand: "Cantillon",
    name: "Cantillon - Cuvée Saint-Gilloise (Champions) (2023)",
    price: 18.99,
    description:
      "Two-year-old lambic in which fresh HallertauMittelfrüh hops have been soaked. A perfect balance is struck between the lambic’s natural acidity and the Hallertau hops’ refined bitterness. Max 1pp.",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHdRalkjDc-TsDmL04ybUJhW6ciNEIB9IaGuHxsGl2CVWUlGAncvbdzqXtIoAQIQpZdU2ZT40G57rSYz9RybOE3akQdhTPPmcUfZBUzl0sGTjIrSdDXruoXFg87W-ASgbpPiUsxnKWJlZWg1jIrnuo1A=w726-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "main",
    tag: "slided_main",
    isPopular: true,
  },
  {
    id: 2,
    brand: "Cantillon",
    name: "Cantillon - Rosé de Gambrinus (2023)",
    price: 16.99,
    description:
      "Blend of lambics and raspberries - 200 g of raspberries per litre of beer. Beer with a slightly acidic, fruity and fragrant taste.",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHdWrEEgkZLL_4OEX9WES0JVozVDmGVqa-0wVWMDj-ckuDXqtEthhDYCu9oD_ba5Q-9wd3jU3s4wZgPsVbsvVl7j5PKMFKnZRk1RYH72llbeWi8Wp0_mfZJ4KdvsqOXeq8gUUYMrW742tsQEumpUirB8=w726-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "main",
    tag: "slided_main",
    isPopular: false,
  },
  {
    id: 3,
    brand: "Cantillon",
    name: "Cantillon - Rosé de Gambrinus (2023) 37,5cl",
    price: 10.49,
    description:
      "Blend of lambics and raspberries - 200 g of raspberries per litre of beer. Beer with a slightly acidic, fruity and fragrant taste.",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHeuUPi8pXqjOQlQpGPenswxbBLt9BbsbjmTu2zBNHUiZqBsnWlM1xqGXACzQHtRH1nf56EGq0BwTxFs0NS_VbH64jr-XrBGmeUunrL10XwGzVFUr2UIi9sJks1Xod-X0fk5ON-YHmJ_FkG_4fO-C1j0=w724-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "main",
    tag: "slided_main",
    isPopular: false,
  },
  {
    id: 4,
    brand: "Cantillon",
    name: "Cantillon - Kriek 100% Lambic Bio (2023)",
    price: 16.99,
    description:
      "Blend of lambics and sour cherries - 200 g of cherries per litre of beer. Beer with a slightly acidic taste of red fruit complemented with subtle almond flavours.",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHfOufqeWCvtJh9P6FSk5KcIUfq5SDw9jG8MHsrPEZXjnQTUzMRnBrryRQgF_d0VtJ-Qvn1FSLrUvypYR8udIZHa3pyNPG3adU05a_p_tiKPw-FC7WbPsxBJypQxmxY-N2WtFh_J8X2AHHAJ8v1Ul-Vr=w724-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "main",
    tag: "slided_main",
    isPopular: false,
  },
  {
    id: 5,
    brand: "Lervig",
    name: "Lervig / Pulpit Rock - Kransekake Stout)",
    price: 5.79,
    description:
      'Imperial Stout with Norwegian “kransekake" added. Immerse your taste buds in a symphony of flavors as sweet vanilla, sugar, coffee, and roasted almonds dance harmoniously on your palate.',
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHfFBbzxPpiYREbcOTORoL51Ekj4YGPHKncqt2xHBlqpzxrVB7oaNKpzkFy2bqDgYjPxMziXYB-5kwX9F1Nqs89855kPn-jHrxaiLFCFRIF-U8w_SGJSxFzF3TS1ejf_tS4c6LGSdn98cMlyCVlJBDBq=w659-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "main",
    tag: "slided_main",
    isPopular: false,
  },
  {
    id: 6,
    brand: "Het Boerenerf",
    name: "Het Boerenerf - Zomerkriek - Oogst 2022",
    price: 25.49,
    description:
      "Blend of lambic macerated with organic cherries and cider. The fruit is blended with lambic then macerated for months. After this, the lambic matures further on barrel. The final blend with cider is done just before bottling.",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHcDh2yj1Bip2Ytf9jZpJrIofsY2Y5NfdGxd_UcZg0yon6IdVgAfMLI4Mg9_9GyXwpfSrymgB-ajQQuUAAQJodBEnGxfREdaOhyJXVbLOk7M3IM3C1B3xKtdQZbGjUysT2Ullh0-pkVBP2qkG4u7cpYk=w659-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "main",
    tag: "slided_main",
    isPopular: false,
  },
  {
    id: 7,
    brand: "Puhaste",
    name: "Pühaste - Surmapatt Sauternes/Port/Whisky BA (Silver Series)",
    price: 9.79,
    description: "Triple barrel aged version of Surmapatt imperial porter.",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHc_Q5lQWnum2X0K0S2_spUA0zSFl1oPlAjmU7Suds4jWGOJ6jn5EbX-6r2yQTGxjQBXSQsEHlvyxZlt9oAIisCNjydgMY7hxsow6SwGfioPvSuruolsn1sOX8BThfHYAg2ewkv02aX5_wAGVrZPmjPU=w659-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "main",
    tag: "slided_main",
    isPopular: false,
  },
  {
    id: 8,
    brand: "Basqueland",
    name: "Basqueland - Prime Time",
    price: 25.49,
    description:
      "Triple IPA with a dry-hop of Mosaic, Vista, Idaho7 and Mosaic Cryo hops for massive aromas: ripe tropical fruit with layers of yellow peach, mandarin zest, pear compote, orange marmalade and green tea.",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHfkw4bXof8xKJ77tnC6o2XSziHMQBJ7HWroiNhlQIcegVDoW9GsxTOXZ1qQ_LtAl-eqChAWZp47RFcPqpczsdmsE170xXUBZjAnrknozy-XiHNGWm3ebHUfLijWA3Qn7fBxGvu3NLC_wwvlK_lWA1_7=w659-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "main",
    tag: "slided_main",
    isPopular: true,
  },
  {
    id: 9,
    brand: "Side Project",
    name: "Shared - Parallels",
    price: 71.99,
    description:
      "A double BA version of the Parfait base - a blend of barrel aged & oak aged Imperial Stouts which were blended and then racked back (double barrel aged) into Willett Barrels. Finished with fresh ground cinnamon sticks, vanilla and barrel aged maple syrup.",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHc7mkdS6iaRoqhMIeSfCh6F5XpFvAj1-51dtw5ogiOAlVplcSoK7SpdoHcwwSogsql6qD4yBJufWDr2u908i-sc3BZyM1_JB1ZWQ-U_iY_U9RSz-_0d2S9d-PQBAyv5KfTCkS0kCOxUlIdt8IExVUWu=w659-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "main",
    tag: "slided_popular",
    isPopular: false,
  },
  {
    id: 10,
    brand: "Folkingbrew",
    name: "Folkingbrew - Dreamscape",
    price: 6.49,
    description:
      "Double New England IPA hopped with Simcoe, Nelson Sauvin & Citra",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHdXgx9PszQh2mHZqK99TbntdGLzoP4gWvYv0ZhtUlpW96WfUeYDQpVqBZ18_4b7vqWG8AWbpEQbnEY_K9yn5-0Ys644xq8tH_7zaZcbU75iSX58aasPTaWpeTfYeOuFz8s3m6XvtmLJPhAJUBsvSyD_=w659-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "main",
    tag: "slided_popular",
    isPopular: false,
  },
  {
    id: 11,
    brand: "Croma",
    name: "Croma - Follow Me (Bourbon Barrel Aged)",
    price: 28.99,
    description:
      "This adjunct-free Imperial Stout offers a distinctive mix of chocolate, coffee and toasted oak flavors, thanks to aging in Four Roses and Woodford Reserve Bourbon barrels. Subtle hints of vanilla and caramel, smooth texture.",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHcdcwOCI5APcXV5Kt39u0ntz2nz7QFtcoaEXEQoRhsJjsiUOkGuROQRC6n44SBdYIJA85FyMgnDfkSn7pwFG_ybk9bqK15vo783MGKYrXwU7uXeGRb0ssx9eeO_vDxbKYPCzPEUAXPKjqmFPpiQa176=w659-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "main",
    tag: "slided_popular",
    isPopular: true,
  },
  {
    id: 12,
    brand: "Spartacus",
    name: "Spartacus - Wolf inside",
    price: 6.49,
    description: "Triple New England IPA with Motueka, Citra and Galaxy hops.",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHfCHqqtyPSwGVeFmNwVkV3M3Bee76krxrWURCjBddYl4INQcRTEYagzNSQCFzXlrOWT82ZsLnPrkb9q50I1CX68M5-yZjTRqraVaT_HR5i_HQ9COEL0G1QJEcIPJL7vNeMD5H8eK7Kv5EuxNJFNp567=w659-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "main",
    tag: "slided_popular",
    isPopular: false,
  },
  {
    id: 13,
    brand: "Folkingbrew",
    name: "Folkingbrew - Under the Sea",
    price: 6.49,
    description:
      "Tropical New England IPA brewed with Cascade and Strata hops, imparting citrus and pine notes. Dry-hopped with Strata, Citra, El Dorado, and Talus, creating juicy fruitiness with flavors of mango, passion fruit and citrus.",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHeTByWqK8IZP7MeNzG1gJSNgErvBAnTm2EID-OySPm6tAXaC-FagXAt-KAiWMaETovX0Ugag2c3Kclpgjv1eBtaBMG1yqmcnUuFoAhAHfAfbCwi2AeoeijIQ46i0KAjK_eYzkirw8vynoakzd0OmNeD=w659-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "main",
    tag: "slided_popular",
    isPopular: false,
  },
  {
    id: 14,
    brand: "FrauGruber",
    name: "FrauGruber - Back To It",
    price: 6.79,
    description: "Double New England IPA with HBC 630.",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHcH8Zx7-gcBpY_y3og4fIMI7g9GL6NcLay082CKitg3ApTKkDYKxiFrIGbr6W-uDiQc3tzg2nShXAi0bnDA2lib1HV4EJ-YTCQEjjwbHFWbHL-PiFueYb0jbFoL1F_dB0tS8zon1fcDzXYMBS3XGmrV=w659-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "main",
    tag: "slided_popular",
    isPopular: false,
  },
  {
    id: 15,
    brand: "CRAK",
    name: "CRAK - Take Me Home",
    price: 6.99,
    description:
      "Take me home, from the Veneto 'para casa', the last beer of the evening, the one you drink before going home. Dense and oily Imperial Stout, with notes of coffee and chocolate and a delicate roasted bitterness at the end.",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHdaXWAaU_zYqzgRSY73-LRgjubZJ5tWwqXmcVoty-Ypr-wyGCJA5xyqduRl6AHpFiUKPB7m0VzfOvsxfj9nMDi8x8uI8ZTORm1ukrRxS3_0CYClk6ji3UCWgmv_Ypj0srf3R93kf2_TTlRgqZ_0vn8k=w659-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "main",
    tag: "slided_popular",
    isPopular: false,
  },
  {
    id: 16,
    brand: "Basqueland",
    name: "Basqueland - Trailblazer",
    price: 6.99,
    description:
      "Walk on this innovative path with dried passion fruit-fused hop blend, Kohia Nelson, from New Zealand. This New England IPA unfolds brilliant aromas and flavors of sweet passion fruit and zesty tangerine that will blow your mind.",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHcUHF5CefjlCY_WwBtP8uZF3pDua2dMxorXUlwq8BObGhYyRp5AfFQnt2kb7PTOjPsJxK9DC0iN8zeDj_cMQbnm6dx_HdqBcJi2NRX1YciVZ8kLMlA2Wol5QbwyuicM_XWmryff2AM4OWT4Xy0Tl6kl=w659-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "main",
    tag: "slided_popular",
    isPopular: false,
  },
  {
    id: 17,
    brand: "Croma",
    name: "Croma - Tropo Rosso (Bourbon Barrel Aged)",
    price: 28.99,
    description:
      "Bourbon barrel aged Barleywine without any adjuncts, aged in a Four Roses barrel.",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHdKKZO-99wvTN4EOcfTSQ7es-VnRYKeqpiXNvR_c8a4zYbXioyL54DLlvccv_GabIGwsMjmdxcsIv3CUJj-U1E-9rdBNs4EZCEpsnqJVJIjKOlAoC903OAgErX4yeHK8eR5Z5gTs2434YBfMKn7h52J=w659-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "style",
    tag: "product",
    isPopular: false,
  },
  {
    id: 18,
    brand: "Brehon Brewhouse",
    name: "Brehon Brewhouse - Raglan Road",
    price: 5.79,
    description:
      "Complimenting notes of Madeira with the sweetness of roasted malts, this robust Whiskey Cask barrel-aged Imperial Stout is rich with notes of chocolate and liquorice. Hopped with Willamette and Magnum. CROWLER! CANNED 10-8, BEST BEFORE 21-9",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHdCNPJ4QjCm6iv1x_W-4el4-kW9I-7yW1cS0KPXjyMUN5HjaaW6yI5OINzBlbu7GOA3lrXNx5s9lwO4cE9GUChtZzB1awEKThj5YPFRmNQi3FZLJz06uqw5FttBd8CsuMe_UYfvmuYrwptRHMOPMI8B=w659-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "style",
    tag: "product",
    isPopular: false,
  },
  {
    id: 19,
    brand: "Toppling Goliath",
    name: "Toppling Goliath - Double Dry Hop King Sue",
    price: 10.99,
    description:
      "Citra hops give King Sue its bold flavors of mango, orange and pineapple. This double dry hopped version packs even more flavor into each can.",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHesass2r1F8Vqa-BM-5SLqBZ7optb6ST_I-e0mihHzj9XOnR88vc9EQWxeK0XPqZbLMkvT3WsXNiMIhmTGNZjbxWUk9BX8muHlZ78LCfkrCixLbwfmYQBxtTZvEDZ0UpdQh5k2JzXXL1e_RAG4VTM0l=w659-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "style",
    tag: "product",
    isPopular: false,
  },
  {
    id: 20,
    brand: "Fremont",
    name: "Fremont - Brew 6000 (2022)",
    price: 36.99,
    description:
      "This English-style barleywine ale uses floor-malted English barley, Noble hops and is aged in 10-15 year-old, single use bourbon barrels for 16 months to bring you a complex and subtle craft beer flavor experience. Brewed to celebrate the 6000th brew!",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHesass2r1F8Vqa-BM-5SLqBZ7optb6ST_I-e0mihHzj9XOnR88vc9EQWxeK0XPqZbLMkvT3WsXNiMIhmTGNZjbxWUk9BX8muHlZ78LCfkrCixLbwfmYQBxtTZvEDZ0UpdQh5k2JzXXL1e_RAG4VTM0l=w659-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "style",
    tag: "product",
    isPopular: false,
  },
  {
    id: 21,
    brand: "450 North",
    name: "450 North - SLUSHY XL Banana Bluntz",
    price: 10.99,
    description:
      "Banana Bluntz XL is conditioned on double banana, orange, passionfruit and banana candies.",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHfkNvSNn0rYour33bRiL79cdhot556yd6ZMF2PCyR6RzC9v7Mb_sz2_Ys3DGi1kfWjrBnM-wuaPDST0tG20uYTChdvOkTCe2ii1WN7_Q_O-XRj0aF5aGhXsiL34S7eZlIZoRnAdwb_PaCfnnatP4P7V=w659-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "country",
    tag: "product",
    isPopular: false,
  },
  {
    id: 22,
    brand: "450 North",
    name: "450 North - SLUSHY XL Space Intruders",
    price: 9.99,
    description:
      "Space Intruders XL is conditioned on double mango, apricot, tangerine, kiwi and coconut.",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHfUBojVI8JWUQgugO-4FzzV-xBaNvLr4XjX0bKIT65S5tpXuTgad4K15h56pC23QL3tCMa989HbukstHWwKMCU8uVXX62YEpQKNgRBeH3_QnFlE8OYwF6GlKxVTLjTGo8yYU1oSihKMbg0A90tz5pJ8=w659-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "country",
    tag: "product",
    isPopular: false,
  },
  {
    id: 23,
    brand: "Ārpus",
    name: "Ārpus / Hop Hooligans - QDH Nelson X Riwaka X Citra Lupomax X Simcoe Cryo TIPA",
    price: 6.49,
    description:
      "Banana Bluntz XL is conditioned on double banana, orange, passionfruit and banana candies.",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHdjTOrSMZN9g0IHc80SnpmXwpExnFSUWId4mY7BasjxFfA0deNsYt_CAXsYDwvTQyWYs9-ywJQHfYP-1eIWdi2MT4D6f60mkK0mH1bms6VenfGTg2a04ktt9mf9f7LYObKN642E0wYqmfywSs6Jl5s-=w659-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "country",
    tag: "product",
    isPopular: false,
  },
  {
    id: 24,
    brand: "450 North",
    name: "450 North - SLUSHY XXL Fishbowl Punch",
    price: 10.99,
    description:
      "Smoothie Sour conditioned on pineapple, lemon, orange, Blue Curacao, sweet and sour mix, coconut cream, nerds candy and Swedish fish.",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHfxvVzIcpfEY5rYamS0vTFsQAW23Z7ne-mINBZCLKsvrnQ0rVTBJm6u1WNkdyrRxjUUNWnQROMO4vwQ0y_jbbQBFXtp3AeN1aORoSlu1YuTfNFAd7oEQ0S7at6C4DTYMyCnDfBaCkhvm4_uZNdMZwB3=w659-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "country",
    tag: "product",
    isPopular: false,
  },
  {
    id: 25,
    brand: "Beerdome",
    name: "Beerdome Bundle",
    price: 29.99,
    description:
      "Package of 6 beers: 1x Vault City - Triple Fruited Mango, 1x Frontaal - Enjoy the Distance, 1x Folkingebrew - Enter the Night, 1x Spartacus - Death Strain, 1x Spartacus - Under the Stars, 1x Poppels - Hazy India Pale Ale",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHcyyt1mE1q4sFTlQ8GszW-tOi-K1SJQ35RtHzSNVYnCKR0ovQ4ntoqsPCkc-yM2XHySlCJ2y2g__0xwbtWvTs81bU6_Zqp9XDP_eNs2HNs9pRARC4R3y5fumJeiV4bLaLX-Qp3TFxJhVOpjSx8_hDxe=w988-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "pack",
    tag: "product",
    isPopular: false,
  },
  {
    id: 26,
    brand: "Brouwerij Kees",
    name: "Kees Bundle",
    price: 24.99,
    description:
      "Package of 6 delicious Kees beers: 1x Bohemian Dream, 1x Barrel Project India Pale Ale 2023, 1x Undisclosed Desires, 1x Orange Trempée (collab with Dochter vd Korenaar), 1x California Sunset 2023, 1x Triple Haze",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHeN1U35rmr1OUQOlsBcU85p6-Nj-2RKVz1lNaS3zuz-HVJaWM8p7iLDmrbrlNNZElpJ_8HmT7XrAWPxKjmebgbAM3iUdSiQqwnHpAEV79vWJVBO-h8Gwc4n7ySNXUeOCocueJY8903Y5wdS_4qNXsHv=w988-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "pack",
    tag: "product",
    isPopular: false,
  },
  {
    id: 27,
    brand: "IPA",
    name: "IPA Bundle",
    price: 33.99,
    description:
      "Bundle with 6 different IPA's: 1x Folkingebrew - Follow the Sun, 1x Spartacus - Death Strain, 1x Kees - Baby Haze, 1x Mad Scientist / Folkingebrew - Quantum Flavourdynamics, 1x Frontaal - For the Love of Hops ´´Red´´, 1x Spartacus - Under the Stars",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHcfyGW_cugkgJBqL5RayYErO97d_wfRKeC-pkNmJkt_p8UfX4UqEpfh_1AIurd2Cwrw98aJBOdzSOiG-8oQaA5YwPHRerunQzU4rK3mvnUMVBrnDdHg2Q5LeE5s73OMnOrMzEyAaH2Mf23_RRI3--r3=w988-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "pack",
    tag: "product",
    isPopular: false,
  },
  {
    id: 28,
    brand: "Dutch",
    name: "Dutch Bundle",
    price: 33.99,
    description: "This package consists of 6 delicious Dutch beers.",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHcx1pvaxEZ9vtVU2m3R21g6Qs4DYY20gTsGgI6J0RgmT-kVgzH0_Bm56u3vjFUUD54uh8HXrfuz93Dkv2l6bFeEu8pYtBcK-df-_N4b91zxLYK1HTT4edOFD7Fa8RZWQEOH95PtjXLXDQZ4ftkr5NKp=w988-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "pack",
    tag: "product",
    isPopular: false,
  },
  {
    id: 29,
    brand: "Funky Fluid",
    name: "Funky Fluid - 4th Anniversary Shaker Glass Gold 50cl",
    price: 5.99,
    description: "Birthday collab glass.",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHfiO-Rdr83FAU7C9UKEwGpHl72d-z2i_KZ-HN-AFurNawBOSRXkuZ1tLd7GdDBvW5Nk-bpqYp7VdS9Jz2PjGGgFkJdBmdo_PXUP-NHOOmrnrsBHBVascsutm4je5qDiftI6dVV2VK27_aFErZ2SXax3=w659-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "glass",
    tag: "product",
    isPopular: false,
  },
  {
    id: 30,
    brand: "Funky Fluid",
    name: "Funky Fluid - Shaker Glass White 50cl",
    price: 5.99,
    description: "Shaker with white Funky Fluid logos.",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHfarDlvZob0kPBWvpBSSCsGVzsAfcEB0AXC8-rEV_HtZxc4xhc29o6YVbMm_iS4Cz4cSt1lEXZxO_TVbXMxnniDEnQ9IgIF2f_FZpShR8AJ0_CFnOIpGYjaeC-uIusxiqnCqtrGJUmqBJ4UVAUQ3drZ=w659-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "glass",
    tag: "product",
    isPopular: false,
  },
  {
    id: 31,
    brand: "Brehon Brewhouse",
    name: "Brehon Brewhouse - Balloon Glass 50cl",
    price: 4.99,
    description: "",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHff7ieXywL8GQqDnXXZBK-gG7I54AEkdkmufGzVT5vibPIHAIytv78OYGijtshLiZhzETQUYwuKdo91hQaRU39zVUOXDJswPaAOJbgIPXFK4bjbMO-hx2e8IGkMBFqf2wTo_C6e0lrJOdYxt-qF6i5T=w659-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "glass",
    tag: "product",
    isPopular: false,
  },
  {
    id: 32,
    brand: "PINTA",
    name: "PINTA - Barrel Brewing Glass 50cl",
    price: 5.99,
    description: "",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHc9EZsZniv7lAEKT8oihzO_RfmL2fYFLeGO5IfWnGpn3UiB8OnB42j7iv0cK-7tAtpNHuFt6DHNqqhHqdVTSDUA0WK4gHGcd5xjYSZQskRUVUY_8pFJEeOiSP_0dylaWLulbQBmUyF6WnqqjbpkOPES=w659-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "glass",
    tag: "product",
    isPopular: false,
  },
  {
    id: 33,
    brand: "Brehon Brewhouse",
    name: "Brehon Brewhouse - Raglan Road",
    price: 4.99,
    description:
      "Complimenting notes of Madeira with the sweetness of roasted malts, this robust Whiskey Cask barrel-aged Imperial Stout is rich with notes of chocolate and liquorice. Hopped with Willamette and Magnum. CROWLER! CANNED 10-8, BEST BEFORE 21-9",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHdCNPJ4QjCm6iv1x_W-4el4-kW9I-7yW1cS0KPXjyMUN5HjaaW6yI5OINzBlbu7GOA3lrXNx5s9lwO4cE9GUChtZzB1awEKThj5YPFRmNQi3FZLJz06uqw5FttBd8CsuMe_UYfvmuYrwptRHMOPMI8B=w659-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "crowler",
    tag: "product",
    isPopular: false,
  },
  {
    id: 34,
    brand: "Lobik",
    name: "Lobik - Ripe Tropicana",
    price: 5.79,
    description:
      "Fruited Sour ale with pineapple, papaya, passionfruit and mango. CROWLER! CANNED 10-8, BEST BEFORE 21-9",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHfo_BcQj3f0i9G3KZRGna8x6rk2t0gt3Bm36tw8vT_lXUaU6IOpoZKSw61iwrASxgHZzfKfAe7zN0LmqVOpreaC0FBTo7iSEmsxpqcD_bkkv5OJPC94CB2CYRuMOd8hZqmdVSkcVhmlpe5ZEifLEM_l=w659-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "crowler",
    tag: "product",
    isPopular: false,
  },
  {
    id: 35,
    brand: "Voucher",
    name: "Digital Voucher - 25 euro",
    price: 25,
    description:
      "25 euro voucher. You'll receive the code per mail after payment is confirmed. Please use the pick-up option to avoid the shipping costs if no other beers are being ordered.",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHexgk0GkRb1fa6i1qeJC_bUzkntPJe2ftnEo03tU_AR-vnI--Ip6pQI12u9afO2ac6JjPbUTl8qPTrFPQzenom48_BBz29AIAR6LbrBuS_kNfwQc5jbEpgJh3nnXzMmVg9oSMDKW9yVv8t4xreWM0i1=w660-h900-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "voucher",
    tag: "product",
    isPopular: false,
  },
  {
    id: 36,
    brand: "Voucher",
    name: "Digital Voucher - 50 euro",
    price: 50,
    description:
      "50 euro voucher. You'll receive the code per mail after payment is confirmed. Please use the pick-up option to avoid the shipping costs if no other beers are being ordered.",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHenzDB5m7ifmDET9mlKgLTdkk5V6SMkgAyV-PXnMXh5RlBoWOU5pPenRbTeh2Se64G5yvUvqr9KmbCLK_qS2bDhdQ_sxQUc5JXw-ezDce6E8uXmM09I9aUFyyLXfHo3r94yJIISyiAyIcEcgL7Ce9-u=w660-h900-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "voucher",
    tag: "product",
    isPopular: false,
  },
  {
    id: 37,
    brand: "Voucher",
    name: "Digital Voucher - 100 euro",
    price: 100,
    description:
      "100 euro voucher. You'll receive the code per mail after payment is confirmed. Please use the pick-up option to avoid the shipping costs if no other beers are being ordered.",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHeySpSXTdsi6E5E-_uroUgi84uJwkobU0p2T6pqbFTiUG0jAlIiS7ceupThByEDojTLMwg7e1yVsf4fLGLdhAhqXjkZ4ljlYMLkjBoTGt-ytvQldUwRxp3ApqW_Aax3HpuNfSwb6OweVV4P1jEiNDfP=w660-h900-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "voucher",
    tag: "product",
    isPopular: false,
  },
  {
    id: 38,
    brand: "Voucher",
    name: "Digital Voucher - 150 euro",
    price: 150,
    description:
      "150 euro voucher. You'll receive the code per mail after payment is confirmed. Please use the pick-up option to avoid the shipping costs if no other beers are being ordered.",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHe0JZQHtEPljg1VnU90g99_U4BIGROHTr0cYUm4Lh8zR6XCf0g4hRutODkT6IuFcj5ctVVY2T_adrvQtmlfjU7w5mz8O0FNFfnxZaYz1MLCGFv_vYFmfbSDg63kCu1iu50-RHv_ssJqW1ErheE5eqm4=w660-h900-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: null,
    type: "voucher",
    tag: "product",
    isPopular: false,
  },
  {
    id: 39,
    brand: "Central Waters",
    name: "Central Waters - Maple Barrel Stout (2022)",
    price: 29.99,
    description:
      "Imperial Stout aged in bourbon barrels, which previously contained B&E's Trees bourbon barrel aged maple syrup, providing the earthy nuttiness of the Wisconsin Maple Trees to an already outstanding barrel aged stout.",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHdRX3Vtmzoz8ksZKD-r5ITxlNflzPrlML5fM9MbTI2-nrwWOu_bEvtlx8ECSOt7eQJwq2zeiT_mN3mss-vvfY10ibhxBr-3cjJjRuJusH_BfDFKWRi6jDLwKGho-RKevRXEE3_XzdvDIw2QXk_TUQ02=w659-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: 39,
    type: "sale",
    tag: "product",
    isPopular: false,
  },
  {
    id: 40,
    brand: "Folkingebrew",
    name: "Folkingebrew - Darkest Hour",
    price: 5.79,
    description: "Imperial Stout with cocoa nibs & vanilla",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHceSFeJ-qeL5rBmN8P9e--_4q7JIQRhYe3qDM5Em5_cANLgrhpgsBwU4ifskoI26eT3f9BK5CHabhDlDH6M0Z2v9UenqZw8JjmvONyy0-F1alb7xk6JBOKi2d8NgMGsSyeeFk2SNY0LxNh1G51zb5k9=w659-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: 6,
    type: "sale",
    tag: "product",
    isPopular: false,
  },
  {
    id: 41,
    brand: "J. Kemker",
    name: "J. Kemker - Appelwien",
    price: 9.99,
    description:
      "Spontaneous fermented cider with apples from the Münsterland and Bielefeld region. Aged for 6 months in oak barrels. BBE: 15-10-2023",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHdr6m2u02WAQDjdK8sF1-Xaeka6IM-wAExaGoTnmUVJ-gs3YghB9xpvdeFkG9u_Elo0AS_cJHbufS4kvO8Y0iwSkjDEezTbFtw-Aza6e4SfKJwS2hBKWc9L6k1F_MeZc3CsUj0WlHNk_wBSRlQ9PY5l=w659-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: 13,
    type: "sale",
    tag: "product",
    isPopular: false,
  },
  {
    id: 42,
    brand: "Lervig",
    name: "Lervig - No Worries - Driving Home For Christmas",
    price: 0.99,
    description:
      "Drive home safe for Christmas with this Non-Alcoholic beer! It offers you all the malty, dark roasted and spice notes of other Christmas beers – but with none of the alcohol!",
    rating: 4,
    imageUrl:
      "https://lh3.googleusercontent.com/pw/ADCreHdjyc6M3s-v7BJMrKXpajZoxrNcBUf2uowlYqUtOqxGWotaNSide0U13J9qoFdPPaPp65foTHPjSl8VnI1nPjftsgFu80eFSikMhWP0o7SGrgAdkibgiXDsobpPtOWAzzh2OF0MiXr9xE4csOdWb3xI=w659-h988-s-no-gm?authuser=0",
    quantity: 1,
    oldPrice: 1,
    type: "sale",
    tag: "product",
    isPopular: false,
  },
];
